"""adding change media to make post_id optionals

Revision ID: 133a7fb1a85f
Revises: f936c3d3e043
Create Date: 2025-10-24 12:40:33.149257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '133a7fb1a85f'
down_revision: Union[str, Sequence[str], None] = 'f936c3d3e043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'post_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'post_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
