"""adding channel and parent field to post

Revision ID: 737ead14d4f7
Revises: 20589bff0e51
Create Date: 2025-10-20 22:01:41.086964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '737ead14d4f7'
down_revision: Union[str, Sequence[str], None] = '20589bff0e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post', sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'post', 'channel', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'post', 'post', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'parent_id')
    op.drop_column('post', 'channel_id')
    # ### end Alembic commands ###
