"""remove_content_index_fix_large_text_issue

Revision ID: abde019daa32
Revises: 69b275ee340a
Create Date: 2025-10-24 22:37:14.808539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'abde019daa32'
down_revision: Union[str, Sequence[str], None] = '69b275ee340a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_content'), table_name='post')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_content'), 'post', ['content'], unique=False)
    # ### end Alembic commands ###
