"""adding emoji to channel

Revision ID: f964687d0ad3
Revises: bfcfeef9d99a
Create Date: 2025-10-23 19:21:10.492689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f964687d0ad3'
down_revision: Union[str, Sequence[str], None] = 'bfcfeef9d99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'emoji')
    # ### end Alembic commands ###
